# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - bdsagroup13chirprazor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  bundle-migrations:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install ef-tool
        run: dotnet tool install --global dotnet-ef

      - name: Bundle migrations
        run: dotnet ef migrations bundle --project src/Chirp.Infrastructure --startup-project src/Chirp.Web

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: efbundle
          path: ./efbundle


  deploy:
    runs-on: ubuntu-latest
    needs: bundle-migrations
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Download migrations bundle from bundle-migrations job
        uses: actions/download-artifact@v4
        with:
          name: efbundle
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5DD2DE376846444D8755E96C905CF90A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_56932E29827F4111B66BFCB9D9017642 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BBAFA8682D384A48AE5DE1A04A011D36 }}

      - name: Apply migrations
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            chmod +x efbundle
            ./efbundle

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bdsagroup13chirprazor'
          slot-name: 'Production'
          package: .
          
