name: Release (and publish)

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write # release prs

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      release_created: ${{ steps.create_release.outputs.release_created }}
    steps:
      - id: create_release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
    
  publish:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rid: [linux-x64, linux-arm64, win-x64, win-arm64, osx-x64, osx-arm64]
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish for ${{ matrix.rid }}
        run: |
          dotnet publish src/Chirp.CLI/Chirp.CLI.csproj \
            -c Release \
            -r ${{ matrix.rid }} \
            -p:PublishSingleFile=false \
            -o publish/${{ matrix.rid }}

      - name: Ensure executable bit (Linux/macOS only)
        if: ${{ matrix.rid != 'win-x64'}}
        run: chmod +x publish/${{ matrix.rid }}/Chirp.CLI || true

      - name: Zip output
        run: |
          cd publish
          zip -r chirp-${{ matrix.rid }}.zip ${{ matrix.rid }}

      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release-please.outputs.upload_url }}
          asset_path: publish/chirp-${{ matrix.rid }}.zip
          asset_name: chirp-${{ github.ref_name }}-${{ matrix.rid }}.zip
          asset_content_type: application/zip
